import type { Metadata } from "next";
import { Bree_Serif, Quicksand } from "next/font/google";
import "./globals.css";
import Logo from "@/public/2minty-logo.svg";
import Link from "next/link";
import { Navbar } from "@/components/layout/navbar";

const breeSerif = Bree_Serif({
  weight: "400",
  variable: "--font-bree-serif",
  subsets: ["latin", "latin-ext"],
});

const quicksand = Quicksand({
  weight: ["400", "500", "600", "700"],
  variable: "--font-quicksand",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${breeSerif.variable} ${quicksand.variable} font-quicksand antialiased`}
      >
        <header>
          <Navbar />
        </header>

        <main>{children}</main>

        <footer></footer>
      </body>
    </html>
  );
}
